CWE-79.c
PHPAP_INI_OFF
PHP_FUNCTION(header_register_callback)
References zend_parse_parameters, zend_is_callable, Z_ADDREF_P.
SAPI_API SAPI_POST_READER_FUNC(sapi_read_standard_form_data)
static char* get_default_content_type(uint prefix_len, uint *len TSRMLS_DC)
References p.
Referenced by sapi_get_default_content_type, sapi_get_default_content_type_header, sapi_send_headers.
SAPI_API void sapi_activate(TSRMLS_D)
References sapi_free_header, request_method, sapi_read_post_data.
SAPI_API void sapi_activate_headers_only(TSRMLS_D)
References sapi_free_header, request_method.
SAPI_API int sapi_add_header_ex(char *header_line, uint header_line_len, zend_bool duplicate, zend_bool replace TSRMLS_DC)
References sapi_header_op.
Referenced by php_session_send_cookie.
SAPI_API size_t sapi_apply_default_charset(char **mimetype, size_t len TSRMLS_DC)
Referenced by sapi_header_op.
SAPI_API void sapi_deactivate(TSRMLS_D)
References sapi_send_headers_free.
static int sapi_extract_response_code(const char *header_line)
Referenced by sapi_header_op.
SAPI_API int sapi_flush(TSRMLS_D)
References SUCCESS.
Referenced by php_exec.
SAPI_API int sapi_force_http_10(TSRMLS_D)
SAPI_API void sapi_free_header(sapi_header_struct *sapi_header)
Referenced by php_session_remove_cookie, sapi_activate, sapi_activate_headers_only, sapi_header_add_op, sapi_remove_header, sapi_send_headers.
SAPI_API char* sapi_get_default_content_type(TSRMLS_D)
References get_default_content_type.
Referenced by php_apache_sapi_send_headers.
SAPI_API void sapi_get_default_content_type_header(sapi_header_struct *default_header TSRMLS_DC)
References get_default_content_type.
Referenced by sapi_send_headers.
SAPI_API int sapi_get_fd(int *fd TSRMLS_DC)
SAPI_API double sapi_get_request_time(TSRMLS_D)
Referenced by php_session_rfc1867_callback.
SAPI_API struct stat* sapi_get_stat(TSRMLS_D)
SAPI_API int sapi_get_target_gid(gid_t *obj TSRMLS_DC)
SAPI_API int sapi_get_target_uid(uid_t *obj TSRMLS_DC)
SAPI_API char* sapi_getenv(char *name, size_t name_len TSRMLS_DC)
References value, PARSE_STRING.
Referenced by amf_tag_contents.
static void sapi_globals_ctor(sapi_globals_struct *sapi_globals TSRMLS_DC)
Referenced by sapi_startup.
static void sapi_globals_dtor(sapi_globals_struct *sapi_globals TSRMLS_DC)
Referenced by sapi_shutdown, sapi_startup.
SAPI_API void sapi_handle_post(void *arg TSRMLS_DC)
static void sapi_header_add_op(sapi_header_op_enum op, sapi_header_struct *sapi_header TSRMLS_DC)
References sapi_remove_header, sapi_free_header.
Referenced by sapi_send_headers, sapi_header_op.
SAPI_API void sapi_initialize_empty_request(TSRMLS_D)
static void sapi_read_post_data(TSRMLS_D)
References p, SUCCESS.
Referenced by sapi_activate.
SAPI_API int sapi_register_default_post_reader(void(*default_post_reader)(TSRMLS_D) TSRMLS_DC)
References SUCCESS.
SAPI_API int sapi_register_input_filter(unsigned int(*input_filter)(int arg, char *var, char **val, unsigned int val_len, unsigned int *new_val_len TSRMLS_DC), unsigned int(*input_filter_init)(TSRMLS_D) TSRMLS_DC)
References SUCCESS.
SAPI_API int sapi_register_post_entries(sapi_post_entry *post_entries TSRMLS_DC)
References p, sapi_register_post_entry, SUCCESS.
SAPI_API int sapi_register_post_entry(sapi_post_entry *post_entry TSRMLS_DC)
Referenced by sapi_register_post_entries.
SAPI_API int sapi_register_treat_data(void(*treat_data)(int arg, char *str, zval *destArray TSRMLS_DC) TSRMLS_DC)
References SUCCESS.
static void sapi_remove_header(zend_llist *l, char *name, uint len)
References sapi_free_header.
Referenced by sapi_header_add_op, sapi_header_op.
static void sapi_run_header_callback(TSRMLS_D)
References zend_fcall_info_init, SUCCESS.
Referenced by sapi_send_headers.
SAPI_API int sapi_send_headers(TSRMLS_D)
References SUCCESS, get_default_content_type, sapi_header_add_op, sapi_run_header_callback, buf, sapi_get_default_content_type_header, sapi_free_header, sapi_send_headers_free.
Referenced by php_apache_sapi_flush, phar_do_403, phar_do_404, phar_file_action, amf_tag_contents.
static void sapi_send_headers_free(TSRMLS_D)
Referenced by sapi_deactivate, sapi_send_headers.
SAPI_API void sapi_shutdown(void)
References sapi_globals_dtor.
Referenced by php_apache_server_shutdown.
SAPI_API void sapi_startup(sapi_module_struct *sf)
References sapi_globals_ctor, sapi_globals_dtor.
Referenced by php_apache_server_startup.
SAPI_API void sapi_terminate_process(TSRMLS_D)
SAPI_API void sapi_unregister_post_entry(sapi_post_entry *post_entry TSRMLS_DC)
static void sapi_update_response_code(int ncode TSRMLS_DC)
Referenced by sapi_header_op.
php_apache_sapi_header_handler(sapi_header_struct *sapi_header, sapi_header_op_enum op, sapi_headers_struct *sapi_headers TSRMLS_DC)
php_apache_sapi_register_variables(zval *track_vars_array TSRMLS_DC)
References key.
int oidc_auth_checker(request_rec *r)
References oidc_authz_get_claims_and_idtoken, if.
static int oidc_authenticate_user(request_rec *r, oidc_cfg *c, oidc_provider_t *provider, const char *original_url, const char *login_hint, const char *id_token_hint, const char *prompt, const char *auth_request_params, const char *path_scope)
References oidc_discovery, oidc_get_browser_state_hash, oidc_authorization_request_set_cookie, p.
Referenced by amf_tag_contents.
static int oidc_authorization_request_set_cookie(request_rec *r, oidc_cfg *c, const char *state, oidc_proto_state_t *proto_state)
References oidc_clean_expired_state_cookies, oidc_get_state_cookie_name.
Referenced by oidc_authenticate_user.
static int oidc_authorization_response_error(request_rec *r, oidc_cfg *c, oidc_proto_state_t *proto_state, const char *error, const char *error_description)
static apr_byte_t oidc_authorization_response_match_state(request_rec *r, oidc_cfg *c, const char *state, struct oidc_provider_t **provider, oidc_proto_state_t **proto_state)
authz_status oidc_authz_checker(request_rec *r, const char *require_args, const void *parsed_require_args, oidc_authz_match_claim_fn_type match_claim_fn)
References oidc_authz_get_claims_and_idtoken.
Referenced by oidc_authz_checker_claim, oidc_authz_checker_claims_expr.
authz_status oidc_authz_checker_claim(request_rec *r, const char *require_args, const void *parsed_require_args)
References oidc_authz_checker.
authz_status oidc_authz_checker_claims_expr(request_rec *r, const char *require_args, const void *parsed_require_args)
References oidc_authz_checker.
static void oidc_authz_get_claims_and_idtoken(request_rec *r, json_t **claims, json_t **id_token)
Referenced by oidc_auth_checker, oidc_authz_checker.
static apr_byte_t oidc_check_cookie_domain(request_rec *r, oidc_cfg *cfg, oidc_session_t *session)
static int oidc_check_max_session_duration(request_rec *r, oidc_cfg *cfg, oidc_session_t *session)
Referenced by amf_tag_contents.
static int oidc_check_mixed_userid_oauth(request_rec *r, oidc_cfg *c)
References oidc_check_userid_openidc.
Referenced by oidc_check_user_id.
int oidc_check_user_id(request_rec *r)
References oidc_check_userid_openidc, oidc_check_mixed_userid_oauth.
static int oidc_check_userid_openidc(request_rec *r, oidc_cfg *c)
References oidc_copy_tokens_to_request_state.
Referenced by amf_tag_contents, oidc_check_mixed_userid_oauth, oidc_check_user_id.
static int oidc_clean_expired_state_cookies(request_rec *r, oidc_cfg *c, const char *currentCookieName, int delete_oldest)
References oidc_delete_oldest_state_cookies.
Referenced by oidc_authorization_request_set_cookie.
int oidc_content_handler(request_rec *r)
static void oidc_copy_tokens_to_request_state(request_rec *r, oidc_session_t *session, const char **s_id_token, const char **s_claims)
Referenced by amf_tag_contents, oidc_check_userid_openidc.
static int oidc_delete_oldest_state_cookies(request_rec *r, int number_of_valid_state_cookies, int max_number_of_state_cookies, oidc_state_cookies_t *first)
Referenced by oidc_clean_expired_state_cookies.
static int oidc_discovery(request_rec *r, oidc_cfg *cfg)
Referenced by oidc_authenticate_user.
static char* oidc_get_browser_state_hash(request_rec *r, const char *nonce)
References value, hash.
Referenced by oidc_authenticate_user.
apr_byte_t oidc_get_provider_from_session(request_rec *r, oidc_cfg *c, oidc_session_t *session, oidc_provider_t **provider)
References p.
apr_byte_t oidc_get_remote_user(request_rec *r, const char *claim_name, const char *reg_exp, const char *replace, json_t *json, char **request_user)
static char* oidc_get_state_cookie_name(request_rec *r, const char *state)
Referenced by oidc_authorization_request_set_cookie.
void AdvanceTime(base::TimeDelta delta)
VideoDetectorTest()
int num_invocations() const
void reset_stats()
virtual ~VideoDetectorTest()
CastCastView* cast_view()
CastSelectDefaultView* select_view()
void ExecuteJavaScript(const std::string &javascript)
References GetRenderViewHost.
Referenced by amf_tag_contents.
void ExecuteJavaScriptWithCallback(const std::string &javascript, const JavaScriptResultCallback &callback)
References GetRenderViewHost.
const extensions::Extension* FindCastExtension()
Referenced by GetRenderViewHost.
void GetReceiversAndActivitiesCallback(const ash::CastConfigDelegate::ReceiversAndActivitesCallback &callback, const base::Value *value)
References value.
content::RenderViewHost* GetRenderViewHost()
References extension, FindCastExtension.
Referenced by amf_tag_contents, ExecuteJavaScript, ExecuteJavaScriptWithCallback.
static LayoutRect AbsoluteToLocal(const LayoutBox &box, LayoutRect rect)
static bool CanHaveOverflowScrollbars(const LayoutBox &box)
ClampScrollableAreas()
Referenced by ~DelayScrollOffsetClampScope.
static int CornerStart(const LayoutBox &box, int min_x, int max_x, int thickness)
DelayScrollOffsetClampScope()
static bool InvalidatePaintOfScrollControlIfNeeded(const LayoutRect &new_visual_rect, const LayoutRect &previous_visual_rect, bool needs_paint_invalidation, LayoutBox &box, const LayoutBoxModelObject &paint_invalidation_container)
Referenced by InvalidatePaintOfScrollbarIfNeeded.
static LayoutRect InvalidatePaintOfScrollbarIfNeeded(Scrollbar *scrollbar, GraphicsLayer *graphics_layer, bool &previously_was_overlay, const LayoutRect &previous_visual_rect, bool needs_paint_invalidation_arg, LayoutBox &box, const PaintInvalidatorContext &context)
References ScrollControlVisualRect, context, InvalidatePaintOfScrollControlIfNeeded.
static bool LayerNodeMayNeedCompositedScrolling(const PaintLayer *layer)
static LayoutRect LocalToAbsolute(const LayoutBox &box, LayoutRect rect)
PaintedOutputOfObjectHasNoEffectRegardlessOfSize() const
static LayoutRect ScrollControlVisualRect(const IntRect &scroll_control_rect, const LayoutBox &box, const PaintInvalidatorContext &context, const LayoutRect &previous_visual_rect)
References context.
Referenced by InvalidatePaintOfScrollbarIfNeeded.
static const LayoutObject& ScrollbarStyleSource(const LayoutBox &layout_box)
~DelayScrollOffsetClampScope()
References ClampScrollableAreas.
bool checkAndSetPrivateFlagOnConsole(const char *name, bool defaultValue)
References ensureConsole, key.
Referenced by reportDeprecatedCall.
void createBoundFunctionProperty(v8::Local< v8::Context > context, v8::Local< v8::Object > console, const char *name, v8::FunctionCallback callback, const char *description=nullptr)
References context, returnDataCallback.
V8InspectorSessionImpl* currentSession()
References ensureInspectedContext.
Referenced by debuggerAgent, profilerAgent.
V8DebuggerAgentImpl* debuggerAgent()
References currentSession.
Referenced by setFunctionBreakpoint.
v8::Local<v8::Object> ensureConsole()
Referenced by checkAndSetPrivateFlagOnConsole, ensureInspectedContext, privateMap.
V8InspectorClient* ensureDebuggerClient()
References ensureInspectedContext.
InspectedContext* ensureInspectedContext()
References ensureConsole, key, inspectedContextPrivateKey.
Referenced by currentSession, ensureDebuggerClient, reportCall.
v8::MaybeLocal<v8::Function> firstArgAsFunction()
v8::MaybeLocal<v8::Object> firstArgAsObject()
bool firstArgToBoolean(bool defaultValue)
String16 firstArgToString(const String16 &defaultValue)
double getDoubleFromMap(v8::Local< v8::Map > map, const String16 &key, double defaultValue)
References key.
int64_t getIntFromMap(v8::Local< v8::Map > map, const String16 &key, int64_t defaultValue)
References key.
v8::Local<v8::Private> inspectedContextPrivateKey(v8::Isolate *isolate)
Referenced by ensureInspectedContext.
static bool isCommandLineAPIGetter(const String16 &name)
v8::MaybeLocal<v8::Map> privateMap(const char *name)
References ensureConsole.
V8ProfilerAgentImpl* profilerAgent()
References currentSession.
void reportCall(ConsoleAPIType type)
Referenced by reportCallWithArgument, reportCallWithDefaultArgument, reportDeprecatedCall.
void reportCall(ConsoleAPIType type, const std::vector< v8::Local< v8::Value >> &arguments)
References ensureInspectedContext.
void reportCallWithArgument(ConsoleAPIType type, const String16 &message)
References reportCall.
void reportCallWithDefaultArgument(ConsoleAPIType type, const String16 &message)
References reportCall.
void reportDeprecatedCall(const char *id, const String16 &message)
References checkAndSetPrivateFlagOnConsole, reportCall.
void returnDataCallback(const v8::FunctionCallbackInfo< v8::Value > &info)
Referenced by createBoundFunctionProperty.
void setDoubleOnMap(v8::Local< v8::Map > map, const String16 &key, double value)
References key, value.
static void setFunctionBreakpoint(ConsoleHelper &helper, v8::Local< v8::Function > function, V8DebuggerAgentImpl::BreakpointSource source, const String16 &condition, bool enable)
References debuggerAgent.
void setIntOnMap(v8::Local< v8::Map > map, const String16 &key, int64_t value)
References key, value.
static void timeEndFunction(const v8::FunctionCallbackInfo< v8::Value > &info, bool timelinePrefix)
static void timeFunction(const v8::FunctionCallbackInfo< v8::Value > &info, bool timelinePrefix)
static V8Debugger* toV8Debugger(v8::Local< v8::Value > data)
References p, data.
v8::Local<v8::Boolean> v8Boolean(bool value, v8::Isolate *isolate)
References value.
Referenced by initializeHolderIfNeeded.
void setFunctionProperty(v8::Local< v8::Context > context, v8::Local< v8::Object > obj, const char *name, v8::FunctionCallback callback, v8::Local< v8::External > external)
References context.
V8InspectorImpl* unwrapInspector(const v8::FunctionCallbackInfo< v8::Value > &info)
AndroidIncognitoObserver(ChromeMetricsServiceClient *parent)
AreNotificationListenersEnabledOnAllProfiles()
std::unique_ptr<metrics::FileMetricsProvider> CreateFileMetricsProvider(bool metrics_reporting_enabled)
References RegisterOrRemovePreviousRunMetricsFile.
void GetExecutableVersionDetails(base::string16 *product_name, base::string16 *version_number, base::string16 *channel_name)
void RegisterFileMetricsPreferences(PrefRegistrySimple *registry)
void RegisterOrRemovePreviousRunMetricsFile(bool metrics_reporting_enabled, const base::FilePath &dir, base::StringPiece metrics_name, metrics::FileMetricsProvider::SourceAssociation association, metrics::FileMetricsProvider *file_metrics_provider)
Referenced by CreateFileMetricsProvider.
IndependentFlattener(MetricsLog *log)
bool IsTestingID(const std::string &id)
void CheckSystemProfile(const SystemProfileProto &system_profile)
References system_profile.
MetricsLogTest()
TestMetricsLog(const std::string &client_id, int session_id, LogType log_type, MetricsServiceClient *client)
ChromeUserMetricsExtension* mutable_uma_proto()
References uma_proto.
const SystemProfileProto& system_profile() const
References uma_proto.
Referenced by CheckSystemProfile, GetFallbackStartupProfile.
const ChromeUserMetricsExtension& uma_proto() const
Referenced by mutable_uma_proto, system_profile.
static v8::Local< v8::Object > classObjectOfPrivateScript(ScriptState *scriptState, String className)
References installPrivateScriptRunner, installPrivateScript.
static v8::Local< v8::Value > compileAndRunPrivateScript(ScriptState *scriptState, String scriptClassName, const char *source, size_t size)
References size, context, importFunction, dumpV8Message.
Referenced by importFunction, installPrivateScript, installPrivateScriptRunner.
static void dumpV8Message(v8::Local< v8::Context > context, v8::Local< v8::Message > message)
References context.
Referenced by compileAndRunPrivateScript, rethrowExceptionInPrivateScript, initializeHolderIfNeeded.
void importFunction(const v8::FunctionCallbackInfo< v8::Value > &args)
References compileAndRunPrivateScript.
Referenced by compileAndRunPrivateScript.
static void installPrivateScript(v8::Isolate *isolate, String className)
References compileAndRunPrivateScript, size.
Referenced by classObjectOfPrivateScript.
static v8::Local< v8::Value > installPrivateScriptRunner(v8::Isolate *isolate)
References compileAndRunPrivateScript.
Referenced by classObjectOfPrivateScript.
void rethrowExceptionInPrivateScript(v8::Isolate *isolate, v8::TryCatch &block, ScriptState *scriptStateInUserScript, ExceptionState::ContextType errorContext, const char *propertyName, const char *interfaceName)
References context, dumpV8Message.
int GetBookmarkDragOperation(content::BrowserContext *browser_context, const BookmarkNode *node)
int GetBookmarkDropOperation(Profile *profile, const ui::DropTargetEvent &event, const bookmarks::BookmarkNodeData &data, const BookmarkNode *parent, int index)
References data, IsValidBookmarkDropLocation, GetPreferredBookmarkDropOperation.
gfx::ImageSkia GetBookmarkFolderIcon(SkColor text_color)
References GetFolderIcon.
gfx::ImageSkia GetBookmarkManagedFolderIcon(SkColor text_color)
References GetFolderIcon.
BookmarkShortcutDisposition GetBookmarkShortcutDisposition(Profile *profile)
Referenced by ShouldRemoveBookmarkThisPageUI.
gfx::ImageSkia GetBookmarkSupervisedFolderIcon(SkColor text_color)
References GetFolderIcon.
gfx::ImageSkia GetFolderIcon(gfx::VectorIconId id, SkColor text_color)
Referenced by GetBookmarkFolderIcon, GetBookmarkManagedFolderIcon, GetBookmarkSupervisedFolderIcon.
int GetPreferredBookmarkDropOperation(int source_operations, int operations)
Referenced by GetBookmarkDropOperation.
void GetURLAndTitleToBookmark(content::WebContents *web_contents, GURL *url, base::string16 *title)
References GetURLToBookmark.
Referenced by amf_tag_contents.
GURL GetURLToBookmark(content::WebContents *web_contents)
Referenced by GetURLAndTitleToBookmark.
bool IsAppsShortcutEnabled(Profile *profile)
Referenced by ShouldShowAppsShortcutInBookmarkBar.
bool IsValidBookmarkDropLocation(Profile *profile, const bookmarks::BookmarkNodeData &data, const BookmarkNode *drop_parent, int index)
References data.
Referenced by GetBookmarkDropOperation.
bool ShouldRemoveBookmarkOpenPagesUI(Profile *profile)
bool ShouldRemoveBookmarkThisPageUI(Profile *profile)
References GetBookmarkShortcutDisposition.
bool ShouldShowAppsShortcutInBookmarkBar(Profile *profile)
References IsAppsShortcutEnabled.
void ToggleBookmarkBarWhenVisible(content::BrowserContext *browser_context)
BookmarkEditorView::EditorNode* AddNewFolder(BookmarkEditorView::EditorNode *parent)
void AddTestData()
References base_path.
void ApplyEdits()
void ApplyEdits(BookmarkEditorView::EditorNode *node)
BookmarkEditorViewTest()
void CreateEditor(Profile *profile, const BookmarkNode *parent, const BookmarkEditor::EditDetails &details, BookmarkEditor::Configuration configuration)
void ExpandAndSelect()
BookmarkNode* GetMutableNode(const std::string &name)
References GetNode.
const BookmarkNode* GetNode(const std::string &name)
References base_path.
Referenced by GetMutableNode.
void NewFolder()
void SetTitleText(const base::string16 &title)
void SetURLText(const base::string16 &text)
bool URLTFHasParent()
std::string base_path() const
Referenced by amf_tag_contents, AddTestData, GetNode.
BookmarkEditorView::EditorTreeModel* editor_tree_model()
void ActivateProfile()
References browser.
Referenced by MaybeActivateProfile.
void AddLaunched(Profile *profile)
bool CanOpenProfileOnStartup(Profile *profile)
void Clear()
Referenced by amf_tag_contents.
void DumpBrowserHistograms(const base::FilePath &output_file)
References WriteFile.
Profile* GetFallbackStartupProfile()
References system_profile.
Profile* GetStartupProfile(const base::FilePath &user_data_dir, const base::CommandLine &command_line)
References GetStartupProfilePath.
base::FilePath GetStartupProfilePath(const base::FilePath &user_data_dir, const base::CommandLine &command_line)
References IsGuestModeEnforced.
Referenced by GetStartupProfile.
bool HasBeenLaunched(const Profile *profile) const
bool HasPendingUncleanExit(Profile *profile)
bool IsGuestModeEnforced(const base::CommandLine &command_line, bool show_warning)
Referenced by GetStartupProfilePath.
void MaybeActivateProfile()
References PostTask, ActivateProfile.
Referenced by set_profile_to_activate.
ProfileLaunchObserver()
void ShowUserManagerOnStartup(const base::CommandLine &command_line)
bool activated_profile()
void set_profile_to_activate(Profile *profile)
References MaybeActivateProfile.
static void initializeHolderIfNeeded(ScriptState *scriptState, v8::Local< v8::Object > classObject, v8::Local< v8::Value > holder)
References context, dumpV8Message, v8Boolean.
content::RenderFrameHost* GetMainFrame(content::RenderFrameHost *rfh)
Referenced by amf_tag_contents.
MockNetworkQualityProvider& mock_network_quality_provider()
static String Decode16BitUnicodeEscapeSequences(const String &string)
Referenced by FullyDecodeString.
static bool FindAttributeWithName(const HTMLToken &token, const QualifiedName &name, size_t &index_of_matching_attribute)
static String FullyDecodeString(const String &string, const WTF::TextEncoding &encoding)
References Decode16BitUnicodeEscapeSequences.
static bool HasName(const HTMLToken &token, const QualifiedName &name)
References ThreadSafeMatch.
static bool IsDangerousHTTPEquiv(const String &value)
References value.
static bool IsHTMLQuote(UChar c)
Referenced by TruncateForScriptLikeAttribute.
static bool IsJSNewline(UChar c)
static bool IsNameOfInlineEventHandler(const Vector< UChar, 32 > &name)
static bool IsNonCanonicalCharacter(UChar c)
static bool IsRequiredForInjection(UChar c)
static bool IsSemicolonSeparatedAttribute(const HTMLToken::Attribute &attribute)
References ThreadSafeMatch.
static bool IsSemicolonSeparatedValueContainingJavaScriptURL(const String &value)
References value.
static bool IsSlash(UChar c)
Referenced by TruncateForSrcLikeAttribute.
static bool IsTerminatingCharacter(UChar c)
Referenced by TruncateForScriptLikeAttribute.
static bool StartsClosingScriptTagAt(const String &string, size_t start)
static bool StartsHTMLCloseCommentAt(const String &string, size_t start)
static bool StartsHTMLOpenCommentAt(const String &string, size_t start)
static bool StartsMultiLineCommentAt(const String &string, size_t start)
static bool StartsOpeningScriptTagAt(const String &string, size_t start)
static bool StartsSingleLineCommentAt(const String &string, size_t start)
bool ThreadSafeMatch(const Vector< UChar, inlineCapacity > &vector, const QualifiedName &qname)
Referenced by HasName, IsSemicolonSeparatedAttribute, TokenExitsForeignContent, TokenExitsInSelect, TokenExitsMath.
static void TruncateForScriptLikeAttribute(String &decoded_snippet)
References IsTerminatingCharacter, IsHTMLQuote.
Referenced by TruncateForSemicolonSeparatedScriptLikeAttribute.
static void TruncateForSemicolonSeparatedScriptLikeAttribute(String &decoded_snippet)
References TruncateForScriptLikeAttribute.
static void TruncateForSrcLikeAttribute(String &decoded_snippet)
References IsSlash.
static void FillHuffmanTable(const JpegHuffmanTable *dc_table, const JpegHuffmanTable *ac_table, VAHuffmanTableBufferJPEGBaseline *huffman_table)
static void FillIQMatrix(const JpegQuantizationTable *q_table, VAIQMatrixBufferJPEGBaseline *iq_matrix)
References size, value.
static void FillSliceParameters(const JpegParseResult &parse_result, VASliceParameterBufferJPEGBaseline *slice_param)
static bool IsVaapiSupportedJpeg(const JpegParseResult &jpeg)
References VaSurfaceFormatForJpeg.
unsigned int VaSurfaceFormatForJpeg(const JpegFrameHeader &frame_header)
Referenced by IsVaapiSupportedJpeg.
base::string16 Elide(const GURL &url, const gfx::FontList &font_list, float available_width, ElisionMethod method)
Referenced by RunProgressiveElisionTest.
url::Component* GetComponent(url::Parsed *parsed, url::Parsed::ComponentType type)
Referenced by RunElisionParsingTest.
void RunElisionParsingTest(const std::vector< ParsingTestcase > &testcases)
References GetComponent.
void RunElisionTest(const std::vector< Testcase > &testcases)
void RunProgressiveElisionTest(const std::vector< ProgressiveTestcase > &testcases, ElisionMethod method)
References max, Elide.
bool IsQueryMatch(const std::string &url_query, const std::string &key, URLQueryElementMatcherCondition::QueryElementType query_element_type, const std::string &value, URLQueryElementMatcherCondition::QueryValueMatchType query_value_match_type, URLQueryElementMatcherCondition::Type match_type)
References key, value.
bool Matches(const URLMatcherCondition &condition, const std::string &text)
Referenced by amf_tag_contents.
char CanonicalSchemeChar(base::char16 ch)
bool CanonicalizePort(const char *spec, const Component &port, int default_port_for_scheme, CanonOutput *output, Component *out_port)
bool CanonicalizePort(const base::char16 *spec, const Component &port, int default_port_for_scheme, CanonOutput *output, Component *out_port)
void CanonicalizeRef(const char *spec, const Component &ref, CanonOutput *output, Component *out_ref)
void CanonicalizeRef(const base::char16 *spec, const Component &ref, CanonOutput *output, Component *out_ref)
bool CanonicalizeScheme(const char *spec, const Component &scheme, CanonOutput *output, Component *out_scheme)
Referenced by amf_tag_contents.
bool CanonicalizeScheme(const base::char16 *spec, const Component &scheme, CanonOutput *output, Component *out_scheme)
bool CanonicalizeUserInfo(const char *username_source, const Component &username, const char *password_source, const Component &password, CanonOutput *output, Component *out_username, Component *out_password)
bool CanonicalizeUserInfo(const base::char16 *username_source, const Component &username, const base::char16 *password_source, const Component &password, CanonOutput *output, Component *out_username, Component *out_password)
bool DoPort(const CHAR *spec, const Component &port, int default_port_for_scheme, CanonOutput *output, Component *out_port)
References buf, WritePortInt.
const CHAR* DoRemoveURLWhitespace(const CHAR *input, int input_len, CanonOutputT< CHAR > *buffer, int *output_len, bool *potentially_dangling_markup)
References IsRemovableURLWhitespace.
Referenced by RemoveURLWhitespace.
bool DoScheme(const CHAR *spec, const Component &scheme, CanonOutput *output, Component *out_scheme)
References IsSchemeFirstChar.
bool DoUserInfo(const CHAR *username_spec, const Component &username, const CHAR *password_spec, const Component &password, CanonOutput *output, Component *out_username, Component *out_password)
bool IsRemovableURLWhitespace(int ch)
Referenced by DoRemoveURLWhitespace.
bool IsSchemeFirstChar(unsigned char c)
Referenced by DoScheme.
const char* RemoveURLWhitespace(const char *input, int input_len, CanonOutputT< char > *buffer, int *output_len, bool *potentially_dangling_markup)
References DoRemoveURLWhitespace.
const base::char16* RemoveURLWhitespace(const base::char16 *input, int input_len, CanonOutputT< base::char16 > *buffer, int *output_len, bool *potentially_dangling_markup)
References DoRemoveURLWhitespace.
void WritePortInt(char *output, int output_len, int port)
Referenced by DoPort.
std::string BytesToHexString(unsigned char bytes[16], int length)
static bool ParsedIsEqual(const Parsed &a, const Parsed &b)
void SetupReplComp(void(Replacements< CHAR >::*set)(const CHAR *, const Component &), void(Replacements< CHAR >::*clear)(), Replacements< CHAR > *rep, const CHAR *str)
void AbortCompilation()
FetchDataLoaderAsWasmModule(ScriptState *script_state)
Referenced by CompileFromResponseCallback.
v8::Local<v8::Promise> GetPromise()
void Trace(blink::Visitor *visitor)
Referenced by inflate, amf_tag_contents, compress_thread, cut_short, finish_jobs, load_read, outb_check, outb_write, parallel_compress, write_thread.
WasmDataLoaderClient()
Referenced by CompileFromResponseCallback.
std::unique_ptr<Permissions> PackPermissionSet(const PermissionSet &set)
References permissions, value.
bool UnpackAPIPermissions(const std::vector< std::string > &permissions_input, const PermissionSet &required_permissions, const PermissionSet &optional_permissions, UnpackPermissionSetResult *result, std::string *error)
References UnpackPermissionWithArguments.
Referenced by UnpackPermissionSet.
std::unique_ptr<UnpackPermissionSetResult> UnpackPermissionSet(const Permissions &permissions_input, const PermissionSet &required_permissions, const PermissionSet &optional_permissions, bool allow_file_access, std::string *error)
References UnpackAPIPermissions, UnpackOriginPermissions.
std::unique_ptr<APIPermission> UnpackPermissionWithArguments(base::StringPiece permission_name, base::StringPiece permission_arg, const std::string &permission_str, std::string *error)
References Read.
Referenced by UnpackAPIPermissions.
void AddExtensionAndGrantPermissions(const Extension &extension)
References extension.
scoped_refptr<const Extension> CreateExtensionWithPermissions(std::unique_ptr< base::Value > permissions, const std::string &name, bool allow_file_access)
References Set, permissions.
Referenced by RunContainsFunction.
PermissionsAPIUnitTest()
bool RunContainsFunction(const std::string &manifest_permission, const std::string &args_string, bool allow_file_access)
References extension, CreateExtensionWithPermissions, browser.
bool RunRequestFunction(const Extension &extension, Browser *browser, const char *args, std::unique_ptr< const PermissionSet > *prompted_permissions_out)
References extension, browser.
std::unique_ptr<base::Value> StringVectorToValue(const std::vector< std::string > &strings)
Browser* browser()
Referenced by amf_tag_contents, ActivateProfile, RunContainsFunction, RunRequestFunction.
void AddPattern(URLPatternSet *extent, const std::string &pattern)
scoped_refptr<const Extension> CreateExtensionWithOptionalPermissions(std::unique_ptr< base::Value > optional_permissions, std::unique_ptr< base::Value > permissions, const std::string &name)
References Set, permissions.
PermissionsUpdaterTestDelegate()
void Reset()
void Wait()
Referenced by amf_tag_contents.
const Extension* extension() const
Referenced by amf_tag_contents, ReadCTAPGetInfoResponse, ktypes2str, GetRenderViewHost, AddExtensionAndGrantPermissions, RunContainsFunction, RunRequestFunction.
const PermissionSet* permissions() const
Referenced by security_dump_masked_av, amf_tag_contents, PackPermissionSet, CreateExtensionWithPermissions, CreateExtensionWithOptionalPermissions.
UpdatedExtensionPermissionsInfo::Reason reason() const
Referenced by rose_disconnect, kvm_task_switch, dev_error, handle_task_switch, cm_format_rej, cm_issue_rej, ib_send_cm_rej, security_dump_masked_av, on_check_config, on_handler_vanished, amf_tag_contents, ssh_packet_read_poll_seqnr, ktypes2str.
bool received_notification() const
static bool TokenExitsForeignContent(const CompactHTMLToken &token)
References ThreadSafeMatch.
static bool TokenExitsInSelect(const CompactHTMLToken &token)
References ThreadSafeMatch.
static bool TokenExitsMath(const CompactHTMLToken &token)
References ThreadSafeMatch.
SAPI_API int sapi_header_op(sapi_header_op_enum op, void *arg TSRMLS_DC)
References sapi_update_response_code, SUCCESS, p, sapi_remove_header, sapi_extract_response_code, sapi_apply_default_charset, request_method, sapi_header_add_op.
Referenced by phar_do_403, phar_do_404, phar_file_action, amf_tag_contents, sapi_add_header_ex.
static int php_handler(request_rec *r)
References php_server_context_cleanup, PHPAP_INI_OFF, php_apache_sapi_log_message_ex, php_apache_request_ctor, SUCCESS, last_modified, highlight_file, if, php_apache_request_dtor.
Referenced by php_ap2_register_hook, amf_tag_contents.
void StopCast()
References StopCastCallback.
void StopCastCallback(CastConfigDelegate *cast_config, const CastConfigDelegate::ReceiversAndActivites &receivers_activities)
Referenced by StopCast.
base::string16 FormatBookmarkURLForDisplay(const GURL &url)
std::string GetUploadData(const std::string &brand)
References data.
UserInitiatedInfo CreateUserInitiatedInfo(content::NavigationHandle *navigation_handle, PageLoadTracker *committed_load)
void DoCanonicalizeRef(const CHAR *spec, const Component &ref, CanonOutput *output, Component *out_ref)
void CompileFromResponseCallback(const v8::FunctionCallbackInfo< v8::Value > &args)
References FetchDataLoaderAsWasmModule, WasmDataLoaderClient.
Referenced by WasmCompileStreamingImpl.
void WasmCompileStreamingImpl(const v8::FunctionCallbackInfo< v8::Value > &args)
References CompileFromResponseCallback.
bool UnpackOriginPermissions(const std::vector< std::string > &origins_input, const PermissionSet &required_permissions, const PermissionSet &optional_permissions, bool allow_file_access, UnpackPermissionSetResult *result, std::string *error)
Referenced by UnpackPermissionSet.
static bool TokenExitsSVG(const CompactHTMLToken &token)