CWE-78.c
COPY_ARRAY_PARAM
CASE
another_hunk(enum diff difftype, bool rev)
References context, set_hunkmax, get_line, buf, next_intuit_at, savestr, fatal, format_linenum, pch_hunk_beg, remove_prefix, malformed, grow_hunkmax, incomplete_line, savebuf, say, min, max, pch_swap, pch_write_line.
best_name(char *const *name, int const *ignore)
References OLD, prefix_components, name_is_valid.
fetchmode(char const *str)
Referenced by intuit_diff_type.
get_ed_command_letter(char const *line)
References p.
Referenced by do_ed_script, intuit_diff_type, manager_recv_cb.
get_line(void)
References pget_line.
Referenced by another_hunk, do_ed_script, manager_recv_cb.
get_sha1(char **sha1, char const *start, char const *end)
grow_hunkmax(void)
Referenced by another_hunk.
incomplete_line(void)
Referenced by another_hunk.
malformed(void)
References fatal, format_linenum, buf.
Referenced by another_hunk.
maybe_reverse(char const *name, bool nonexistent, bool is_empty)
References ok_to_reverse.
Referenced by intuit_diff_type.
name_is_valid(char const *name)
References say.
Referenced by best_name.
next_intuit_at(file_offset file_pos, lin file_line)
Referenced by another_hunk, do_ed_script, intuit_diff_type, open_patch_file, manager_recv_cb.
open_patch_file(char const *filename)
References pfatal, fatal, buf, read_fatal, next_intuit_at.
pch_c_function(void)
pch_char(lin line)
bool pch_copy(void)
References OLD.
pch_end(void)
pch_first(void)
pch_git_diff(void)
pch_hunk_beg(void)
Referenced by another_hunk.
pch_line_len(lin line)
pch_mode(bool which)
pch_name(enum nametype type)
pch_newfirst(void)
pch_prefix_context(void)
pch_ptrn_lines(void)
bool pch_rename(void)
References OLD.
pch_repl_lines(void)
pch_says_nonexistent(bool which)
pch_sha1(bool which)
pch_suffix_context(void)
pch_swap(void)
References set_hunkmax.
Referenced by another_hunk.
pch_timestr(bool which)
pch_write_line(lin line, FILE *file)
Referenced by another_hunk.
pfetch(lin line)
pget_line(size_t indent, int rfc934_nesting, bool strip_trailing_cr, bool pass_comments_through)
References read_fatal, buf, say.
Referenced by intuit_diff_type, get_line.
prefix_components(char *filename, bool checkdirs)
References count, f.
Referenced by best_name.
re_patch(void)
set_hunkmax(void)
Referenced by open_patch_file, pch_swap, another_hunk.
sha1_says_nonexistent(char const *sha1)
skip_hex_digits(char const *str)
Referenced by intuit_diff_type.
skip_to(file_offset file_pos, lin file_line)
References say, read_fatal.
Referenced by there_is_another_patch.
there_is_another_patch(bool need_header, mode_t *file_type)
References say, intuit_diff_type, fatal, format_linenum, skip_to, ask, buf.
restore_page_device(const gs_gstate *pgs_old, const gs_gstate *pgs_new)
References gs_currentdevice.
Referenced by z2grestoreall.
z2grestoreall(i_ctx_t *i_ctx_p)
References restore_page_device.
static RELOC_PTRS_WITH(device_reloc_ptrs, gx_device *dev)
References gx_device_reloc_ptr.
static RELOC_PTRS_WITH(device_forward_reloc_ptrs, gx_device_forward *fdev)
References gx_device_reloc_ptr.
gs_closedevice(gx_device *dev)
Referenced by gs_main_finit, pdf14_forward_put_params, pdf14_put_params, gs_setdevice_no_init, gx_device_finalize.
gs_copydevice(gx_device **pnew_dev, const gx_device *dev, gs_memory_t *mem)
References gs_copydevice2.
Referenced by gs_pdf14_device_push, pdf14_create_clist_device, manager_recv_cb.
gs_copydevice2(gx_device **pnew_dev, const gx_device *dev, bool keep_open, gs_memory_t *mem)
References gx_device_make_struct_type, gx_device_init, gx_device_set_procs.
Referenced by gs_copydevice.
gs_copypage(gs_gstate *pgs)
References gs_output_page.
gs_copyscanlines(gx_device *dev, int start_y, byte *data, uint size, int *plines_copied, uint *pbytes_copied)
References gx_device_raster, count, size, data.
gs_currentdevice(const gs_gstate *pgs)
Referenced by PreserveTrMode, gs_main_init2, restore_page_device, gs_flushpage, gs_output_page.
gs_deviceinitialmatrix(gx_device *dev, gs_matrix *pmat)
gs_devicename(const gx_device *dev)
gs_flushpage(gs_gstate *pgs)
References gs_currentdevice.
gs_getdefaultdevice(void)
References gs_getdefaultlibdevice.
gs_getdefaultlibdevice(gs_memory_t *mem)
References count, gs_getdevice.
Referenced by gs_getdefaultdevice.
gs_getdevice(int index)
References count.
Referenced by gs_getdefaultlibdevice.
gs_gstate_putdeviceparams(gs_gstate *pgs, gx_device *dev, gs_param_list *plist)
References gs_gstate_update_device.
gs_gstate_update_device(gs_gstate *pgs, gx_device *dev)
Referenced by gs_gstate_putdeviceparams, gs_setdevice_no_init.
bool gs_is_null_device(gx_device *dev)
gs_make_null_device(gx_device_null *dev_null, gx_device *dev, gs_memory_t *mem)
References gx_device_init, gx_device_copy_color_params.
gs_opendevice(gx_device *dev)
Referenced by pdf14_forward_open_device, gs_setdevice_no_erase.
gs_output_page(gs_gstate *pgs, int num_copies, int flush)
References gs_currentdevice.
Referenced by gs_copypage.
gs_setdevice_no_erase(gs_gstate *pgs, gx_device *dev)
References gs_lib_ctx_get_interp_instance, gsicc_init_iccmanager, gsicc_init_device_profile_struct, gsicc_set_device_profile_intent, gs_opendevice, gs_setdevice_no_init.
Referenced by manager_recv_cb.
gs_setdevice_no_init(gs_gstate *pgs, gx_device *dev)
References gs_closedevice, gs_gstate_update_device.
Referenced by gs_setdevice_no_erase.
bool gx_color_info_equal(const gx_device_color_info *p1, const gx_device_color_info *p2)
gx_device_adjust_resolution(gx_device *dev, int actual_width, int actual_height, int fit)
References min, max, gx_device_set_width_height.
gx_device_close_output_file(const gx_device *dev, const char *fname, FILE *file)
References gx_parse_output_file_name.
gx_device_copy_color_params(gx_device *dev, const gx_device *target)
References gx_device_copy_color_procs.
Referenced by gs_make_null_device, gx_device_copy_params.
gx_device_copy_color_procs(gx_device *dev, const gx_device *target)
Referenced by gx_device_copy_color_params.
gx_device_copy_params(gx_device *dev, const gx_device *target)
References COPY_ARRAY_PARAM, gx_device_copy_color_params.
Referenced by pdf14_forward_open_device, pdf14_forward_put_params.
int gx_device_delete_output_file(const gx_device *dev, const char *fname)
References gx_parse_output_file_name.
gx_device_enum_ptr(gx_device *dev)
gx_device_finalize(const gs_memory_t *cmem, void *vptr)
References gs_closedevice.
Referenced by pdf14_device_finalize, gx_device_free_local.
gx_device_free_local(gx_device *dev)
References gx_device_finalize.
gx_device_init(gx_device *dev, const gx_device *proto, gs_memory_t *mem, bool internal)
Referenced by gs_copydevice2, gs_make_null_device.
gx_device_init_on_stack(gx_device *dev, const gx_device *proto, gs_memory_t *mem)
gx_device_make_struct_type(gs_memory_struct_type_t *st, const gx_device *dev)
Referenced by gs_copydevice2.
gx_device_open_output_file(const gx_device *dev, char *fname, bool binary, bool positionable, FILE **pfile)
References gx_parse_output_file_name.
gx_device_raster(const gx_device *dev, bool pad)
References if.
Referenced by pdf14_clist_create_compositor, gs_copyscanlines.
gx_device_raster_chunky(const gx_device *dev, bool pad)
gx_device_raster_plane(const gx_device *dev, const gx_render_plane_t *render_plane)
References if.
gx_device_reloc_ptr(gx_device *dev, gc_state_t *gcst)
Referenced by RELOC_PTRS_WITH.
gx_device_retain(gx_device *dev, bool retained)
gx_device_set_hwsize_from_media(gx_device *dev)
Referenced by gx_device_set_media_size, gx_device_set_resolution.
gx_device_set_margins(gx_device *dev, const float *margins, bool move_origin)
References if.
gx_device_set_media_from_hwsize(gx_device *dev)
Referenced by gx_device_set_width_height.
gx_device_set_media_size(gx_device *dev, double media_width, double media_height)
References gx_device_set_hwsize_from_media.
gx_device_set_procs(gx_device *dev)
Referenced by pdf14_recreate_device, gs_copydevice2.
gx_device_set_resolution(gx_device *dev, double x_dpi, double y_dpi)
References gx_device_set_hwsize_from_media.
gx_device_set_width_height(gx_device *dev, int width, int height)
References gx_device_set_media_from_hwsize.
Referenced by gx_device_adjust_resolution.
gx_finish_output_page(gx_device *dev, int num_copies, int flush)
gx_outputfile_is_separate_pages(const char *fname, gs_memory_t *memory)
References gx_parse_output_file_name.
gx_parse_output_file_name(gs_parsed_file_name_t *pfn, const char **pfmt, const char *fname, uint fnlen, gs_memory_t *memory)
References gx_parse_output_format.
Referenced by gx_device_close_output_file, gx_device_delete_output_file, gx_device_open_output_file, gx_outputfile_is_separate_pages.
gx_parse_output_format(gs_parsed_file_name_t *pfn, const char **pfmt)
References max.
Referenced by gx_parse_output_file_name.
gx_set_device_only(gs_gstate *pgs, gx_device *dev)
ivalidate_clean_spaces(i_ctx_t *i_ctx_p)
Referenced by zsave, manager_recv_cb.
zsave(i_ctx_t *i_ctx_p)
References ivalidate_clean_spaces.
MacroExpander(const Solid::Device &device)
Referenced by manager_recv_cb.
PHP_FUNCTION(exec)
References php_exec_ex.
PHP_FUNCTION(system)
References php_exec_ex.
PHP_FUNCTION(passthru)
References php_exec_ex.
PHPAPI char* php_escape_shell_cmd(char *str)
References p.
PHPAPI int php_exec(int type, char *cmd, zval *array, zval *return_value TSRMLS_DC)
References buf, sig_handler, sapi_flush, add_next_index_stringl.
Referenced by php_exec_ex.
static void php_exec_ex(INTERNAL_FUNCTION_PARAMETERS, int mode)
References zend_parse_parameters, php_exec.
Referenced by PHP_FUNCTION.
static uint64_t get_free_space_available(const char *path)
static void vdagent_file_xfer_task_free(gpointer data)
References data.
Referenced by vdagent_file_xfers_create.
struct vdagent_file_xfers* vdagent_file_xfers_create(struct udscs_connection *vdagentd, const char *save_dir, int open_save_dir, int debug)
References vdagent_file_xfer_task_free.
static int add_server(struct manager_ctx *manager, struct server *server)
References check_port.
Referenced by manager_recv_cb.
static int check_port(struct manager_ctx *manager, struct server *server)
References create_and_bind.
Referenced by add_server.
static int create_and_bind(const char *host, const char *port, int protocol)
References setsockopt, bind.
Referenced by check_port.
create_server_socket(const char *host, const char *port)
References setsockopt, bind.
Referenced by manager_recv_cb.
destroy_server(struct server *server)
Referenced by remove_server, manager_recv_cb.
static char * get_action(char *buf, int len)
References buf.
Referenced by manager_recv_cb.
get_data(char *buf, int len)
References data, buf.
Referenced by get_server, parse_traffic, manager_recv_cb.
static struct server* get_server(char *buf, int len)
References data, get_data, buf, value.
Referenced by manager_recv_cb.
static int parse_traffic(char *buf, int len, char *port, uint64_t *traffic)
References data, get_data, buf, value.
Referenced by manager_recv_cb.
static void kill_server(char *prefix, char *pid_file)
References f.
Referenced by manager_recv_cb.
static void stop_server(char *prefix, char *port)
References f.
Referenced by remove_server, manager_recv_cb.
static void remove_server(char *prefix, char *port)
References destroy_server, stop_server.
Referenced by manager_recv_cb.
static void update_stat(char *port, uint64_t traffic)
Referenced by amf_tag_contents, manager_recv_cb.
static void manager_recv_cb(EV_P_ ev_io *w, int revents)
References buf, get_action, get_server, get_data, destroy_server, remove_server, add_server, parse_traffic, update_stat, data, value, kill_server, f, main, option, usage, bind, create_server_socket, stop_server, count, p, grow, size, help, key, hash, CASE, do_ed_script, pfatal, get_line, next_intuit_at, get_ed_command_letter, copy_file, fatal, gs_copydevice, gs_setdevice_no_erase, ivalidate_clean_spaces, MacroExpander.