CWE-352.c
UNCURL_EXPORT int32_t uncurl_accept(struct uncurl_tls_ctx *uc_tls, struct uncurl_conn *ucc, struct uncurl_conn **ucc_new_in, int32_t scheme)
References uncurl_new_conn, uncurl_attach_net, uncurl_attach_tls.
static void uncurl_attach_net(struct uncurl_conn *ucc)
Referenced by uncurl_accept, uncurl_connect.
static void uncurl_attach_tls(struct uncurl_conn *ucc)
Referenced by uncurl_accept, uncurl_connect.
UNCURL_EXPORT int8_t uncurl_check_header(struct uncurl_conn *ucc, char *name, char *subval)
Referenced by uncurl_read_body_all.
UNCURL_EXPORT void uncurl_close(struct uncurl_conn *ucc)
UNCURL_EXPORT int32_t uncurl_connect(struct uncurl_tls_ctx *uc_tls, struct uncurl_conn *ucc, int32_t scheme, char *host, uint16_t port)
References uncurl_attach_net, uncurl_attach_tls.
static void uncurl_default_opts(struct uncurl_opts *opts)
Referenced by uncurl_new_conn.
UNCURL_EXPORT void uncurl_free_header(struct uncurl_conn *ucc)
UNCURL_EXPORT void uncurl_free_info(struct uncurl_info *uci)
UNCURL_EXPORT void uncurl_free_tls_ctx(struct uncurl_tls_ctx *uc_tls)
Referenced by uncurl_new_tls_ctx.
UNCURL_EXPORT int32_t uncurl_get_header(struct uncurl_conn *ucc, char *key, int32_t *val_int, char **val_str)
References key.
UNCURL_EXPORT void uncurl_get_socket(struct uncurl_conn *ucc, void *socket)
UNCURL_EXPORT int32_t uncurl_get_status_code(struct uncurl_conn *ucc, int32_t *status_code)
Referenced by uncurl_ws_connect.
UNCURL_EXPORT int32_t uncurl_listen(struct uncurl_conn *ucc, char *bind_ip4, uint16_t port)
UNCURL_EXPORT struct uncurl_conn* uncurl_new_conn(struct uncurl_conn *parent)
References uncurl_default_opts.
Referenced by uncurl_accept.
UNCURL_EXPORT int32_t uncurl_new_tls_ctx(struct uncurl_tls_ctx **uc_tls_in)
References uncurl_free_tls_ctx.
UNCURL_EXPORT int32_t uncurl_parse_url(char *url, struct uncurl_info *uci)
UNCURL_EXPORT int32_t uncurl_poll(struct uncurl_conn *ucc, int32_t timeout_ms)
UNCURL_EXPORT int32_t uncurl_read_body_all(struct uncurl_conn *ucc, char **body, uint32_t *body_len)
References uncurl_check_header, uncurl_response_body_chunked.
static int32_t uncurl_read_chunk_len(struct uncurl_conn *ucc, uint32_t *len)
Referenced by uncurl_response_body_chunked.
UNCURL_EXPORT int32_t uncurl_read_header(struct uncurl_conn *ucc)
References uncurl_read_header_.
Referenced by uncurl_ws_connect, uncurl_ws_accept.
static int32_t uncurl_read_header_(struct uncurl_conn *ucc, char **header)
Referenced by uncurl_read_header.
static int32_t uncurl_response_body_chunked(struct uncurl_conn *ucc, char **body, uint32_t *body_len)
References uncurl_read_chunk_len.
Referenced by uncurl_read_body_all.
UNCURL_EXPORT int32_t uncurl_set_cacert(struct uncurl_tls_ctx *uc_tls, char *cacert, size_t size)
References size.
UNCURL_EXPORT int32_t uncurl_set_cacert_file(struct uncurl_tls_ctx *uc_tls, char *cacert_file)
UNCURL_EXPORT int32_t uncurl_set_cert_and_key_file(struct uncurl_tls_ctx *uc_tls, char *cert_file, char *key_file)
UNCURL_EXPORT void uncurl_set_header_int(struct uncurl_conn *ucc, char *name, int32_t value)
References value.
UNCURL_EXPORT void uncurl_set_header_str(struct uncurl_conn *ucc, char *name, char *value)
References value.
Referenced by uncurl_ws_connect, uncurl_ws_accept.
UNCURL_EXPORT void uncurl_set_option(struct uncurl_conn *ucc, int32_t opt, int32_t val)
UNCURL_EXPORT int32_t uncurl_write_body(struct uncurl_conn *ucc, char *body, uint32_t body_len)
UNCURL_EXPORT int32_t uncurl_write_header(struct uncurl_conn *ucc, char *str0, char *str1, int32_t type)
Referenced by uncurl_ws_connect, uncurl_ws_accept.
UNCURL_EXPORT int32_t uncurl_ws_close(struct uncurl_conn *ucc, uint16_t status_code)
References uncurl_ws_write.
UNCURL_EXPORT int32_t uncurl_ws_connect(struct uncurl_conn *ucc, char *path, char *origin)
References uncurl_set_header_str, uncurl_write_header, uncurl_read_header, uncurl_get_status_code.
UNCURL_EXPORT int32_t uncurl_ws_read(struct uncurl_conn *ucc, char *buf, uint32_t buf_len, uint8_t *opcode)
References buf.
UNCURL_EXPORT int32_t uncurl_ws_write(struct uncurl_conn *ucc, char *buf, uint32_t buf_len, uint8_t opcode)
References buf.
Referenced by uncurl_ws_close.
UNCURL_EXPORT int32_t uncurl_ws_accept(struct uncurl_conn *ucc, char **origins, int32_t n_origins)
References uncurl_read_header, uncurl_set_header_str, uncurl_write_header.